name: Docker Image CI

on:
  push:
    branches: 
      - dev  # Trigger on pushes to the dev branch
  pull_request:
    branches: 
      - dev  # Trigger on pull requests targeting the dev branch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Updated to the latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Updated to the latest version
        with:
          context: .
          push: true  # Push the image to Docker Hub
          tags: wirewrex/nginx-hns:33443  # Replace with your desired image name and tag
